# Generated by Django 3.0.1 on 2020-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(default='', max_length=10)),
                ('img', models.ImageField(default='', upload_to='static/')),
            ],
        ),
    ]
