# Generated by Django 3.0.1 on 2020-05-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='Names',
        ),
    ]
