# Generated by Django 3.0.1 on 2020-05-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_photos_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
